id: I9D7DB177
ocr_import_info:
  timestamp: '2023-09-28T04:49:42.933278+00:00'
  batch_id: batch-1bf4
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 10:24:13.806776+00:00
last_modified: 2023-09-28 10:24:13.806784+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM1127
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM1127
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱས་པའི་བསྟན་བཅོས་ཚད་མ་རྣམ་འགྲེལ་གྱི་རྒྱ་ཆེར་བཤད་པ་རིགས་པའི་རྒྱ་མཚོ་ལས་མངོན་སུམ་ལེའུའི་རྣམ་བཤད།
  languages:
  - bo
  author: མཁས་གྲུབ་རྗེ་དགེ་ལེགས་དཔལ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.97281466232332
  ocr_word_median_confidence_index: 0.99937236
bases:
  I1NLM1127_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM1127_001
      total_pages: 438
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM1127_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.99937236
      ocr_word_mean_confidence_index: 0.97281466232332
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
